# Generated by Django 3.2.8 on 2022-02-10 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adviser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('honorofic_title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Prof', 'Prof')], default='Mr', max_length=4)),
                ('level', models.PositiveSmallIntegerField(choices=[(100, '100'), (200, '400'), (300, '300'), (400, '400'), (500, '500')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Adviser', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
