# Generated by Django 3.2.8 on 2022-02-16 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('level_adviser', '0002_auto_20220210_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adviserprofile', to=settings.AUTH_USER_MODEL, verbose_name='Account'),
        ),
    ]
