# Generated by Django 3.2.8 on 2022-02-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'level adviser'), (3, 'student')], default=3)),
                ('level', models.PositiveSmallIntegerField(blank=True, choices=[(100, '100'), (200, '400'), (300, '300'), (400, '400'), (500, '500')], null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_adviser', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
