# Generated by Django 3.2.8 on 2022-02-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_account_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='login_counter',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
