# Generated by Django 3.2.8 on 2022-02-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_account_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='level',
            field=models.CharField(blank=True, choices=[(100, '100'), (200, '200'), (300, '300'), (400, '400'), (500, '500'), ('ALUMNI', 'ALUMNI')], max_length=255, null=True),
        ),
    ]
