# Generated by Django 3.2.8 on 2022-02-12 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0003_auto_20220212_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocuments',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_document', to=settings.AUTH_USER_MODEL),
        ),
    ]
